imageType:
  Original: {}
  LoG:
    sigma: [1.0, 2.0, 3.0] 
  Wavelet: {}
featureClass:
  shape:
  firstorder:
  glcm:  
  glrlm:
  glszm:
  gldm:
  ngtdm:
setting:
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [1, 1, 1]
  padDistance: 10  
  binWidth: 25
  voxelArrayShift: 1000  
  label: 1
